/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Nicolas
 */
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencia.Conexion;
import persistencia.InscripcionData;
import persistencia.MateriaData;
import persistencia.AlumnoData;

public class VistaNota extends javax.swing.JInternalFrame {
  private Conexion conexion = new Conexion("jdbc:mysql://localhost/universidad", "root", "");
  private InscripcionData inscripcionData= new InscripcionData(conexion);
  private AlumnoData alumnoData = new AlumnoData(conexion);  
  private MateriaData materiaData = new MateriaData(conexion);
  private List <Inscripcion> lista;
  private List<Inscripcion> listaOriginal;
  
    /**
     * Creates new form vis
     */
    public VistaNota() {
        initComponents();  
        armarTabla();
        cargarcombo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInscripcion = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ListaAlumnoCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbGUARDAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        TablaInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaInscripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaInscripcion);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ListaAlumnoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaAlumnoComboItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de alumno:");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Nota");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));

        jbGUARDAR.setText("Guardar");
        jbGUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGUARDARMouseClicked(evt);
            }
        });
        jbGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGUARDARActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Para modificar la nota, haga click sobre la casilla a modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jbGUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(ListaAlumnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(90, 90, 90))))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaAlumnoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaInscripcionMouseClicked

    }//GEN-LAST:event_TablaInscripcionMouseClicked

    private void ListaAlumnoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaAlumnoComboItemStateChanged
        borrarFilasTablas();
        cargarFilas();
    }//GEN-LAST:event_ListaAlumnoComboItemStateChanged

    private void jbGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGUARDARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGUARDARActionPerformed

    private void jbGUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGUARDARMouseClicked
    Alumno alumno = (Alumno) ListaAlumnoCombo.getSelectedItem();
    
    for (int fila = 0; fila < TablaInscripcion.getRowCount(); fila++) {
        int idMateria = (int) TablaInscripcion.getValueAt(fila, 0);
        Inscripcion inscripcionOriginal = listaOriginal.get(fila);
        double valorNota = Double.parseDouble(TablaInscripcion.getValueAt(fila, 2).toString());

        if (inscripcionOriginal.getNota() != valorNota) {
            System.out.println("Actualizando nota para materia " + idMateria + " a " + valorNota);
            inscripcionData.actualizarNota(alumno.getIdAlumno(), idMateria, valorNota);
        }
        System.out.println("Alumno: " + alumno.getIdAlumno());
        System.out.println("Materia: " + idMateria);
        System.out.println("Nueva Nota: " + valorNota);
    }
    
    // Refrescamos la tabla
    borrarFilasTablas();
    cargarFilas();
    }//GEN-LAST:event_jbGUARDARMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ListaAlumnoCombo;
    private javax.swing.JTable TablaInscripcion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGUARDAR;
    // End of variables declaration//GEN-END:variables
private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            return columna == 2;
        }
 };
    private void cargarcombo(){ 
        for (Alumno alumno:alumnoData.listaAlumno()) 
            ListaAlumnoCombo.addItem(alumno);
            
    }
    private void armarTabla(){
        modelo.addColumn("Codigo"); 
        modelo.addColumn("Materia");
        modelo.addColumn("Nota"); 
        TablaInscripcion.setModel(modelo);
    }
      private void cargarFilas() {
       Alumno alum = (Alumno) ListaAlumnoCombo.getSelectedItem();
       lista = inscripcionData.obtenerInscripcionesPorAlumno(alum.getIdAlumno());
       listaOriginal = new ArrayList<>(lista);
       for  (Inscripcion insc :lista) {
       Materia mat = insc.getMateria();
        modelo.addRow(new Object[]{
        mat.getId_materia(),
        mat.getNombre(),
        insc.getNota()
           });
        
        }     
    }
        private void borrarFilasTablas(){
        int fila= modelo.getRowCount()-1;
        for (int i = fila ; i >= 0 ; i--) {
            modelo.removeRow(i);
        }
    }
}
